--Create the product table--
CREATE TABLE PRODUCT(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);

INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE)VALUES
('1', 'CHATS', '1', '1', '10 PURSES * 20 BAGS', 18),
('2', 'CHANG', '1', '1', '24 * 12 OZ BUTTLES', 19),
('3', 'SYRUP', '1', '2', '12 * 550 ML BOTTLES', 10),
('4', 'SEASONING', '2', '2', '28 * 6 OZ JARS', 22),
('5', 'MIX', '2', '2', '36 PURSES ', 21.35);

--QUERY TO COUNT A NUMBER OF PRODUCTS
SELECT COUNT (PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCT;

--QUERY TO FIND THE AVERAGE PRICE OF PRODUCTS
SELECT AVG (PRICE) AS AVERAGE_PRICE
FROM PRODUCT;

--QUERY TO FIND TOTAL PRICE OF PRODUCTS
SELECT SUM (PRICE) AS TOTAL_PRICE
FROM PRODUCT;